version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
