doctrine:
  dbal:
    driver: 'pdo_pgsql'
    url: '%env(DATABASE_URL)%'
    charset: utf8
    default_table_options:
      charset: utf8
      collate: utf8_unicode_ci
    types:
      email: VDOLog\Core\Infrastructure\Doctrine\Type\Common\EMailType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    mappings:
      VDOLog:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/Core/Infrastructure/Doctrine/Mapping"
        prefix: 'VDOLog\Core\Domain'
        alias: VDOLog
