framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%env(APP_LOCALE)%'

    serializer:
        enable_annotations: false

    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true
