security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'sodium'
  providers:
    web_provider:
      id: VDOLog\Web\Security\WebUserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: web_provider
      form_login:
        login_path: vdo_login
        check_path: vdo_login
      logout:
        path: vdo_logout
      custom_authenticator: VDOLog\Web\Security\WebAuthenticator
  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: '^/', roles: ROLE_USER }
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
