services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: vdolog
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: vdolog
    ports:
      - "5432:5432"

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ".:/usr/src/app"
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    restart: on-failure
    volumes:
      - "./:/usr/src/app"
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/cert:/opt/usr/cert
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - php
