version: 2
jobs:
    build:
        docker:
            -   image: circleci/php:7.4-node-browsers
        working_directory: ~/repo
        steps:
            - checkout
            -   run:
                    name: Configure PHP for VDOLog
                    command: |
                        sudo apt update
                        sudo apt install -y libpng-dev
                        sudo -E docker-php-ext-install gd
            -   run:
                    name: Install PHP Dependencies
                    command: |
                        sudo composer self-update
                        composer install -n --prefer-dist
            -   run:
                    name: Install NodeJS Dependencies
                    command: |
                        curl -o- -L https://yarnpkg.com/install.sh | sudo bash
                        yarn install
                        yarn run build
            -   run:
                    name: Checking CodeStyle with PHPCS
                    command: |
                        make check-cs
            -   run:
                    name: Run Behat feature tests
                    command: |
                        make feature-tests