parameters:
    locale: 'de'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Twig\Extensions\IntlExtension:
        tags: ['twig.extension']

    Twig\Extensions\DateExtension:
        tags: ['twig.extension']
