parameters:
  locale: 'de'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $projectDir: '%kernel.project_dir%'

  _instanceof:
    Twig\Extension\ExtensionInterface:
      tags: [ 'twig.extension' ]

    Doctrine\Common\EventSubscriber:
      tags: [ 'doctrine.event_subscriber' ]

  VDOLog\Core\Application\:
    resource: '../src/Core/Application/*'

  VDOLog\Web\:
    resource: '../src/Web/*'
    exclude: '../src/Web/{Model,Kernel.php}'

  VDOLog\Web\Controller\:
    resource: '../src/Web/Controller'
    tags: [ 'controller.service_arguments' ]

  VDOLog\CLI\Command\:
    resource: '../src/CLI/Command'
    tags: [ 'console.command' ]

  VDOLog\Web\Model\ApplicationConfiguration:
    arguments:
      - [ '%kernel.project_dir%/config/phpdesktop/settings.json', '%kernel.project_dir%/../settings.json' ]

  VDOLog\Core\Domain\GameRepository: '@VDOLog\Core\Infrastructure\Doctrine\DoctrineGameRepository'
  VDOLog\Core\Domain\Game\ReminderRepository: '@VDOLog\Core\Infrastructure\Doctrine\DoctrineReminderRepository'
  VDOLog\Core\Domain\ProtocolRepository: '@VDOLog\Core\Infrastructure\Doctrine\DoctrineProtocolRepository'
  VDOLog\Core\Domain\UserRepository: '@VDOLog\Core\Infrastructure\Doctrine\DoctrineUserRepository'

  VDOLog\Core\Infrastructure\Doctrine\:
    resource: '../src/Core/Infrastructure/Doctrine/*'

  Symfony\Component\PasswordHasher\Hasher\SodiumPasswordHasher: ~

