on:
    push:
        branches:
            - master

name: Build

jobs:
    phpdesktop:
        name: build phpdesktop
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'

            -   name: setup yarn
                run: |
                    curl -o- -L https://yarnpkg.com/install.sh | sudo bash
                    yarn install

            -   name: do application build
                run: make phpdesktop

            -   uses: actions/upload-artifact@v2
                with:
                    name: VDOLog-PHPDesktop
                    path: build
