on:
    - pull_request
    - push

name: CI

jobs:
    security-check:
        name: checking for security issues
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   name: do security check
                run: |
                    wget https://get.sensiolabs.org/security-checker.phar
                    php security-checker.phar security:check

    coding-guidelines:
        name: check code style and static analysis
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   name: linting php files
                run: make lint-php

            -   name: install php dependencies
                run: |
                    sudo composer self-update
                    composer install -n --prefer-dist

            -   name: checking code style
                run: make check-cs

            -   name: doing static analyses with phpstan
                run: make static-analysis

    feature-tests:
        name: running behat feature tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   name: setup yarn for frontend assets
                run: |
                    curl -o- -L https://yarnpkg.com/install.sh | sudo bash
                    yarn install
                    yarn run build

            -   name: install php dependencies
                run: |
                    sudo composer self-update
                    composer install -n --prefer-dist

            -   name: running behat tests
                run: make feature-tests

    unit-tests:
        name: running unit tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   name: install php dependencies
                run: |
                    sudo composer self-update
                    composer install -n --prefer-dist

            -   name: running unit tests
                run: make phpunit
