on:
  - pull_request
  - push

name: CI

jobs:
  coding-guidelines:
    name: Checking CodeStyle with PHPCS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install PHP Dependencies
      run: |
        sudo composer self-update
        composer install -n --prefer-dist

    - name: Checking CodeStyle with PHPCS
      run: make check-cs

    - name: Checking Static Code with PHPStan
      run: make static-analysis

  feature-tests:
    name: Running Behat feature tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install Yarn
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | sudo bash
        yarn install
        yarn run build

    - name: Install PHP Dependencies
      run: |
        sudo composer self-update
        composer install -n --prefer-dist

    - name: Running Behat feature tests
      run: make feature-tests