name: CI
on:
    pull_request: ~
    push:
        branches:
            - master
jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '7.4' ]
                # Excluded cause experimental is not the same as allow failure
                # @see https://github.com/actions/toolkit/issues/399
                # include:
                #    -   php: '8.0'
                #        composer-options: "--ignore-platform-reqs"
                #        experimental: true

        name: PHP ${{ matrix.php }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   uses: "ramsey/composer-install@v1"
                with:
                    composer-options: ${{ matrix.composer-options }}

            - name: setup yarn for frontend assets
              run: |
                curl -o- -L https://yarnpkg.com/install.sh | sudo bash
                yarn install
                yarn run build

            -   name: Linting PHP
                run: make lint-php

            -   name: PHPCS Code Style Check
                run: make check-cs

            -   name: PHPStan Static Analyses
                run: make static-analysis

            -   name: Unit Tests
                run: make phpunit

            -   name: Behat Feature Tests
                run: make feature-tests
